### ISSUE TITLE
last character is missing because last 'ETX' is missing

### ISSUE THREAD

**Issue by doom-fr** [nilpotence/node-ivy#4]
When I send ivy messages with ivy-node and listen with ivy-python (python3), the last character of the last  parameter is missing.
I have made a wireshark sniffing and I observe this :
```
ivy-node :		32:20:30:02:64:65:66:61:75:6c:74:03:31:39:32:30:03:31:32:30:30:0a
ivy-python3 :		32:20:30:02:64:65:66:61:75:6c:74:03:31:39:32:30:03:31:32:30:30:03:0a
ivymon :		32:20:30:02:64:65:66:61:75:6c:74:03:31:39:32:30:03:31:32:30:30:03:0a

translated message of ivy-python and ivymon : 2: :0:0:stx:d:e:f:a:u:l:t:etx:1:9:2:0:etx:1:2:0:0:etx:lf
```

So it seems that ivy-node doesn't put the last 'ETX' before the 'LF' ending.

I haven't seen the frame format documentation, so I am not sure of the correct answer, but it seems that the problem is from ivy-node.

D.

**Comment by doom-fr** [comment]
seems that just removing this line is the solution :
`params = params.substr(0, params.length-1);;`

**Comment by doom-fr** [comment]
If you can also check that messages are well received if they have been sended with the last 'ETX'.
thx

**Comment by doom-fr** [comment]
Maybe it is a not a problem of node-ivy.
I am checking ... stay tuned!

**Comment by sbigaret** [comment]
Hi everyone,
(ivy-python maintainer here, cf. https://gitlab.com/ivybus/ivy-python)
I can confirm that existing ivy implementations do expect a trailing ETX after the last parameter (at least the one I know: ivy-c, ivy-java, ivy-python, and probably others otherwise similar problems would have raised sooner).
And yes, this is so even if the Ivy Protocol says that parameters are separated by ETX ;)

As doom-fr demonstrated above, this can be confirmed by examining the tcp conversation between to 'ivyprobe' e.g. (ivyprobe being directly built on ivy-c, the reference implementation).

As a result,

1. ivy-node should send this extra ETX,
2. and it should expect it when receiving messages as well, or it will suffer from the same kind of bug as the one reported here when dealing with other implementations.

Best regards,
__ Sébastien.

**Comment by doom-fr** [comment]
Here is the documentation of frame format : https://www.eei.cena.fr/products/ivy/documentation/ivy-protocol/x99.html

This paragraph describe the message frame format :

> 2: Text message. The identifier is the identifier of the subscription that was sent by the peer, and whose regular expression matches the text message the application wants to send. The parameters are the substrings of the text message that were captured by the regular expression, separated by ETX (ASCII code 3) characters. If there is no capture in the regular expression (like in "hello .*"), no parameter is sent. An example with a capture would be "hello (.*)". Then, for a "hello world" message, there would be one parameter in the message: "world".

Personally, I think that extra ETX is not expected in Ivy protocol, but added in most implementation by facility. In C implementation which uses strtok for received messages, extra ETX is ignored in reception if present.
In java some similar behavior exists. In python, code has been added to do this (with a little issue that raises the problem of the missing character).
So both format is accepted by these implementations.

So for me, it is not a problem from node-ivy.
However, as most of implementation add the extra ETX, it is a good question to choose between following the documentation (which is nearly clear : a full frame example is just missing) and following the existing implementations (which is the easier solution).

Personally I would choose to not add the extra ETX when sending, but add extra code to accept both frame format in reception. Python module should so be updated to accept correctly both frame format in reception.

But there is also work for @nilpotence (or me when I have some time :-) ) as what I have observed is that extra ETX is not in sended messages, but is expected in reception ! This could not work !

```
function parseTextMessage(peer, identifier, params){
	for(k in subscriptions){
		if(subscriptions[k].id === parseInt(identifier)){
			var msgs = params.split("\u0003");
			if(msgs && msgs.length > 0) msgs.splice(msgs.length-1, 1);
			subscriptions[k].cb(msgs);
		}
	}
}
```
for example :
```
> function test(params) {
	var msgs = params.split("\u0003");
	if(msgs && msgs.length > 0)
		msgs.splice(msgs.length-1, 1);
	return(msgs);
}
undefined
> test('param1\u0003param2\u0003')
[ 'param1', 'param2' ]
> test('param1\u0003param2')
[ 'param1' ]
```

Something like that should work : 
```
function parseTextMessage(peer, identifier, params){
	for(k in subscriptions){
		if(subscriptions[k].id === parseInt(identifier)){
			var msgs = params.split("\u0003");
			if(msgs[msgs.length-1]==='')
				msgs.pop();
			subscriptions[k].cb(msgs);
		}
	}
}
```

```
> function test2(params) { msgs = params.split("\u0003"); if(msgs[msgs.length-1]==='') msgs.pop(); return(msgs); }
undefined
> test2('param1\u0003param2\u0003')
[ 'param1', 'param2' ]
> test2('param1\u0003param2')
[ 'param1', 'param2' ]
```

For both @nilpotence & @sbigaret thanks for your modules, these are usefull for me !

D.

**Comment by doom-fr** [comment]
After having a discussion with initial authors, it has been decided that last ETX is needed and documentation will be updated.

**Comment by doom-fr** [comment]
Merci. Et merci pour la mise à jour sur NPM.
